language: android
jdk:
    - oraclejdk7
android:
  components:
    - build-tools-21.1.1
    - android-21
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'
script:
    - ./gradlew clean assemble check
